# version: '3.8'

services:
  # eureka server
  eureka-server:
    build:
      context: . # 빌드 컨텍스트를 프로젝트 root 폴더로 설정
      dockerfile: ./eureka-server/Dockerfile # 서버 모듈의 Dockerfile 경로 지정
    container_name: eureka-server-container
    ports:
      - "8761:8761"

  # eureka gateway
  eureka-gateway:
    build:
      context: . # 빌드 컨텍스트를 프로젝트 root 폴더로 설정
      dockerfile: ./eureka-gateway/Dockerfile # 클라이언트 모듈의 Dockerfile 경로 지정
    container_name: eureka-gateway-container
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server

  # oauth2-service
  oauth2-service:
    build:
      context: . # 빌드 컨텍스트를 프로젝트 root 폴더로 설정
      dockerfile: ./oauth2-service/Dockerfile # 클라이언트 모듈의 Dockerfile 경로 지정
    container_name: oauth2-service-container
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server

  # user service
  user-service:
    build:
      context: . # 빌드 컨텍스트를 프로젝트 root 폴더로 설정
      dockerfile: ./user-service/Dockerfile # 클라이언트 모듈의 Dockerfile 경로 지정
    container_name: user-service-container
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server

  streaming-db:
    image: postgres:latest
    container_name: streaming-db
    ports:
      - "6000:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin0070
      POSTGRES_DB: STR_DB
    volumes:
      - streaming-db-data:/var/lib/postgresql/data

volumes:
  streaming-db-data:


