server:
  port: 8080

spring:
  application:
    name: eureka-gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
              include-expression: "serviceId.matches('.*-service')"
              filters:
                - StripPrefix=1               # 기본 필터 적용
                - name: CircuitBreaker        # 모든 서비스에 Circuit Breaker 적용
                  args:
                    name: default-circuit-breaker
                    fallback: forward:/fallback
          routes:
#            - id: openapi-aggregate
#              uri: http://localhost:8080
#              predicates:
#                - Path=/api/**
#              filters:
#                - RewritePath=/api/(?<segment>.*), /api/$\{segment}

#            - id: openapi-aggregate
#              uri: http://localhost:8080
#              predicates:
#                - Path=/v3/api-docs/**
#              filters:
#                - RewritePath=/v3/api-docs/(?<segment>.*), /v3/api-docs

            # TODO API Client 추가할때마다 라우팅 규칙 추가 (유연한 방법 고민 필요)
            - id: oauth2-service
              uri: lb://oauth2-service
              predicates:
                - Path=/api/**
              filters:
                - RewritePath=/api/(?<segment>.*), /api/$\{segment}

            - id: oauth2-service
              uri: lb://oauth2-service
              predicates:
                - Path=/v3/api-docs/oauth2-service
              filters:
                - RewritePath=/v3/api-docs/(?<segment>.*), /v3/api-docs

  main:
    web-application-type: reactive

springdoc:
  swagger-ui:
    url: /v3/api-docs
    use-root-path: true
    validator-url: ""

eureka:
  client:
    service-url:
      defaultZone: 'http://host.docker.internal:8761/eureka/'
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${server.port} #ip 주소로 등록
    lease-renewal-interval-in-seconds: 30  # 하트비트 간격(기본 30초)
    lease-expiration-duration-in-seconds: 90  # 등록 만료 시간(기본 90초)
