server:
  port: 8080

spring:
  application:
    name: eureka-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            # TODO API Client 추가할때마다 라우팅 규칙 추가 (유연한 방법 고민 필요)
            - id: oauth2-service
              uri: lb://oauth2-service
              predicates:
                - Path=/api/**
              filters:
                - RewritePath=/api/(?<segment>.*), /api/$\{segment}

            - id: oauth2-service
              uri: lb://oauth2-service
              predicates:
                - Path=/v3/api-docs/oauth2-service
              filters:
                - RewritePath=/v3/api-docs/(?<segment>.*), /v3/api-docs

            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/**
              filters:
                - RewritePath=/api/(?<segment>.*), /api/$\{segment}

            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/v3/api-docs/user-service
              filters:
                - RewritePath=/v3/api-docs/(?<segment>.*), /v3/api-docs

  main:
    web-application-type: reactive

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    url: /swagger-ui.html
    use-root-path: true
    enabled: true
    urls:
      - name: oauth2-service
        url: /v3/api-docs/oauth2-service
      - name: user-service
        url: /v3/api-docs/user-service
#  api-docs:
#    enabled: true
#    path: /v3/api-docs
#  swagger-ui:
#    path: /swagger-ui.html
#    use-root-path: true # 기본 경로를 스웨거 주소로 설정
#    enabled: true
#    config-url: /v3/api-docs/swagger-config
#    urls:
#      - name: eureka-gateway
#        url: /v3/api-docs
#      - name: oauth2-service
#        url: /api/v1/oauth2/v3/api-docs
#    oauth2-redirect-url: /swagger-ui/oauth2-redirect.html

eureka:
  client:
    service-url:
      defaultZone: 'http://host.docker.internal:8761/eureka/'
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${server.port} #ip 주소로 등록
    lease-renewal-interval-in-seconds: 30  # 하트비트 간격(기본 30초)
    lease-expiration-duration-in-seconds: 90  # 등록 만료 시간(기본 90초)
