server:
  port: 8081

spring:
  application:
    name: eureka-user
  config:
    import: oauth2.yml
  data:
    redis:
      host: localhost
      port: 6379
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 0

eureka:
  client:
    service-url:
      defaultZone: 'http://host.docker.internal:8761/eureka/'
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
#    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${server.port} #ip 주소로 등록
    lease-renewal-interval-in-seconds: 30  # 하트비트 간격(기본 30초)
    lease-expiration-duration-in-seconds: 90  # 등록 만료 시간(기본 90초)

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    path: /v3/api-docs

jwt:
  secret: XqJ7f2t+a3V8c3l+Z29xM3p1OHcwMXE0cmQ2czV0N3g5eTJrYWs0bG1uNTVvN3A2cTByc3U3dnk4d3h5ejk=
  expiration-time: 60000 # 만료 시간 (밀리초) 5분
  refresh-expiration-time: 604800000 # 리프레시 토큰 만료 시간 (밀리초) 7일